#!/bin/bash

#Create a PHP Script to Connect to MySQL

sudo nano /var/www/html/testdb.php

sudo chmod 644 /var/www/html/testdb.php

#PHP Code

<?php
// Enable error reporting
error_reporting(E_ALL);
ini_set('display_errors', 1);

// Database credentials
$servername = "localhost";
$username = "dbuser";
$password = "SecurePass123!";
$dbname = "mydatabase";

// Create connection
$conn = new mysqli($servername, $username, $password, $dbname);

// Check connection
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}
echo "Connected successfully";
?>
